# Dependabot configuration for automated dependency updates

version: 2
updates:
  # Enable version updates for npm packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    assignees:
      - 'dorkycam'
    commit-message:
      prefix: 'deps:'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 3
    assignees:
      - 'dorkycam'
    commit-message:
      prefix: 'ci:'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'automated'
