import { InteractiveHearts } from '@/components/particles/InteractiveHearts';
import { InteractivePumpkins } from '@/components/particles/InteractivePumpkins';
import { InteractiveSnow } from '@/components/particles/InteractiveSnow';
import { SleepCountdown } from '@/components/SleepCountdown';
import Head from 'next/head';
import styled from 'styled-components';

const Container = styled.div`
  margin: 0;
  position: relative;
  min-width: 100%;
  height: 100%;
`;

export default function ValentinesDayPage() {
  return (
    <>
      <Head>
        <title>Sleeps &apos;til Valentine&apos;s Day</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <SleepCountdown
            holiday={{
              month: 10,
              day: 31,
              message: 'Happy Halloween!',
              name: 'halloween',
            }}
          />
          <InteractivePumpkins />
        </Container>
      </main>
    </>
  );
}
