import { InteractiveSnow } from '@/components/InteractiveSnow';
import { SleepCountdown } from '@/components/SleepCountdown';
import Head from 'next/head';
import styled from 'styled-components';

const Container = styled.div`
  margin: 0;
  position: relative;
  min-width: 100%;
  height: 100%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Sleeps &apos;till Christmas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <SleepCountdown />
          <InteractiveSnow />
        </Container>
      </main>
    </>
  );
}
