# Production Deployment Workflow
# Runs tests, builds, and deploys to production when pushing to main branch

name: Deploy to Production

on:
  push:
    branches: ['main']

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Run build test
        run: yarn build

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test # Only deploy if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS EB CLI
        run: pip install awsebcli --upgrade --user

      - name: Deploy to production
        run: yarn deploy
